Intent to make changes
ruuvi/ruuvi.drivers.c pull request #180
Opened 2021-01-31 15:49 UTC by DG12

This Pull Request is simply to state the changes I am finishing up.
Minimal functional changes. 
Add comments,.
Move constants to .h
Add function packet_loader to fill a test packet with interesting hexadecimal data because any utility to receive the test packets will (most  likely)  not present text.

2021-02-01 14:25 UTC, ojousima requested changes

2021-02-01 14:25 UTC, ojousima commented on src/integration_tests/ruuvi_interface_communication_ble_gatt_test.c
> + *       2021-01-26 niksiboxi  fixup JSON
Remove these, version history is in git and changelog as appropriate

2021-02-01 14:40 UTC, ojousima commented
> Add function packet_loader to fill a test packet with interesting hexadecimal data because any utility to receive the test packets will (most likely) not present text.

Sounds ok to me as long as it gets compiled only on test/debug builds, i.e. not on releases

2021-02-01 14:41 UTC, ojousima commented
> Move constants to .h

Only if the constants are required by something else than ruuvi_interface_communication_ble_gatt_test.c. Let's keep the externally visible variables as few as possible.

2021-02-20 16:10 UTC, DG12 commented
Nearing completion.

2021-02-20 16:10 UTC, closed without merging